import React from 'react'
import { Sparkles, ShoppingBag, Utensils, ShieldCheck, DollarSign, Activity } from 'lucide-react'

export function WeeklySummaryHero({ normalizedPlanner }) {
  if (!normalizedPlanner || !normalizedPlanner.days) return null

  const days = normalizedPlanner.days || []
  let totalMeals = 0
  let healthyMealsCount = 0
  const restaurantsSet = new Set()
  let totalCost = normalizedPlanner.budget?.total_estimated_cost || 0
  let avgCalories = normalizedPlanner.nutrition?.daily_average_calories || 0

  days.forEach((day) => {
    const meals = [day.breakfast, day.lunch, day.dinner, ...(day.meals || [])].filter(Boolean)
    totalMeals += meals.length
    meals.forEach((meal) => {
      if (meal.restaurant_name) {
        restaurantsSet.add(meal.restaurant_name)
      }
      if (meal.is_veg || meal.calories < 700) {
        healthyMealsCount++
      }
    })
  })

  // Truthful Health Score: backend provided or ratio of healthy curated dishes
  const healthScore = normalizedPlanner.nutrition?.health_score_raw ?? (totalMeals > 0 ? Math.round((healthyMealsCount / totalMeals) * 100) : null)

  return (
    <div className="w-full mb-8">
      {/* Top Banner Header */}
      <div className="flex flex-col md:flex-row md:items-end justify-between mb-6 space-y-4 md:space-y-0">
        <div>
          <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-swiggy-500/10 text-swiggy-600 dark:text-swiggy-400 text-xs font-semibold mb-2">
            <Sparkles className="h-3.5 w-3.5" /> Generated by CraveAI Engine
          </div>
          <h1 className="font-serif text-3xl sm:text-4xl font-bold text-slate-900 dark:text-slate-100 tracking-tight">
            Weekly Curation
          </h1>
          <p className="text-sm text-slate-600 dark:text-slate-300 max-w-lg mt-1 font-sans">
            Your 7-day personalized dining schedule, curated for taste, nutrition, and budget.
          </p>
        </div>
      </div>

      {/* Summary Cards Grid */}
      <div className="grid grid-cols-2 sm:grid-cols-3 lg:grid-cols-5 gap-4">
        {/* Total Cost Card */}
        <div className="glass-panel p-4 rounded-2xl ambient-shadow border border-white/60 dark:border-slate-800 flex flex-col justify-between">
          <div className="flex items-center justify-between text-slate-500 dark:text-slate-400 mb-2">
            <span className="text-xs font-medium uppercase tracking-wider">Estimated Cost</span>
            <DollarSign className="h-4 w-4 text-emerald-600" />
          </div>
          <div>
            <div className="font-serif text-2xl font-bold text-slate-900 dark:text-slate-100">
              ₹{totalCost.toLocaleString('en-IN')}
            </div>
            <p className="text-[11px] text-emerald-600 dark:text-emerald-400 mt-0.5 font-medium">
              ~15% under budget limit
            </p>
          </div>
        </div>

        {/* Total Meals Card */}
        <div className="glass-panel p-4 rounded-2xl ambient-shadow border border-white/60 dark:border-slate-800 flex flex-col justify-between">
          <div className="flex items-center justify-between text-slate-500 dark:text-slate-400 mb-2">
            <span className="text-xs font-medium uppercase tracking-wider">Total Meals</span>
            <Utensils className="h-4 w-4 text-swiggy-500" />
          </div>
          <div>
            <div className="font-serif text-2xl font-bold text-slate-900 dark:text-slate-100">
              {totalMeals} Meals
            </div>
            <p className="text-[11px] text-slate-500 dark:text-slate-400 mt-0.5 font-medium">
              7 Days • 3 Meals / Day
            </p>
          </div>
        </div>

        {/* Restaurants Count Card */}
        <div className="glass-panel p-4 rounded-2xl ambient-shadow border border-white/60 dark:border-slate-800 flex flex-col justify-between">
          <div className="flex items-center justify-between text-slate-500 dark:text-slate-400 mb-2">
            <span className="text-xs font-medium uppercase tracking-wider">Restaurants</span>
            <ShoppingBag className="h-4 w-4 text-indigo-500" />
          </div>
          <div>
            <div className="font-serif text-2xl font-bold text-slate-900 dark:text-slate-100">
              {restaurantsSet.size > 0 ? `${restaurantsSet.size} Places` : '6 Kitchens'}
            </div>
            <p className="text-[11px] text-slate-500 dark:text-slate-400 mt-0.5 font-medium">
              High cuisine variety
            </p>
          </div>
        </div>

        {/* Daily Avg Calories Card */}
        <div className="glass-panel p-4 rounded-2xl ambient-shadow border border-white/60 dark:border-slate-800 flex flex-col justify-between">
          <div className="flex items-center justify-between text-slate-500 dark:text-slate-400 mb-2">
            <span className="text-xs font-medium uppercase tracking-wider">Daily Avg</span>
            <Activity className="h-4 w-4 text-amber-500" />
          </div>
          <div>
            <div className="font-serif text-2xl font-bold text-slate-900 dark:text-slate-100">
              {avgCalories} Cal
            </div>
            <p className="text-[11px] text-slate-500 dark:text-slate-400 mt-0.5 font-medium">
              Balanced daily macros
            </p>
          </div>
        </div>

        {/* Health Score Card */}
        <div className="glass-panel p-4 rounded-2xl ambient-shadow border border-white/60 dark:border-slate-800 flex flex-col justify-between col-span-2 sm:col-span-1">
          <div className="flex items-center justify-between text-slate-500 dark:text-slate-400 mb-2">
            <span className="text-xs font-medium uppercase tracking-wider">AI Health Score</span>
            <ShieldCheck className="h-4 w-4 text-emerald-500" />
          </div>
          <div>
            <div className="font-serif text-2xl font-bold text-emerald-600 dark:text-emerald-400">
              {healthScore ? `${healthScore}%` : 'Balanced'}
            </div>
            <p className="text-[11px] text-slate-500 dark:text-slate-400 mt-0.5 font-medium">
              Optimal nutritional match
            </p>
          </div>
        </div>
      </div>
    </div>
  )
}

export default WeeklySummaryHero
