"""Pydantic data models for Generalized Recommendation Engine (Stage 2C update)."""

from typing import Any, Dict, List, Optional
from pydantic import BaseModel, Field


from enum import Enum


class ConstraintSource(str, Enum):
    USER = "USER"
    MEMORY = "MEMORY"
    DEFAULT = "DEFAULT"
    SYSTEM = "SYSTEM"
    RECOVERY = "RECOVERY"


class ConstraintPriority(str, Enum):
    HARD = "HARD"
    MEDIUM = "MEDIUM"
    SOFT = "SOFT"


class ConstraintScope(str, Enum):
    PERSISTENT = "PERSISTENT"
    SESSION = "SESSION"
    EPHEMERAL = "EPHEMERAL"


class ConstraintExpiration(str, Enum):
    NEVER = "NEVER"
    DOMAIN_SWITCH = "DOMAIN_SWITCH"
    NEXT_TURN = "NEXT_TURN"
    MANUAL_CLEAR = "MANUAL_CLEAR"


class Constraint(BaseModel):
    """Generalized constraint representing a single eligibility filter with Stage 3.3 metadata."""
    type: str  # e.g., "budget", "preference", "meal_type", "health_goal", "restaurant", "spicy", "vegan", "gluten_free"
    value: Any
    is_hard: bool = True
    source: ConstraintSource = ConstraintSource.USER
    priority: ConstraintPriority = ConstraintPriority.HARD
    scope: ConstraintScope = ConstraintScope.SESSION
    expires: ConstraintExpiration = ConstraintExpiration.DOMAIN_SWITCH
    created_turn: int = 1
    expires_turn: Optional[int] = None



class RecommendationContext(BaseModel):
    """Contextual signal information that influences ranking without restricting eligibility."""
    session_id: Optional[str] = None
    raw_query: Optional[str] = None
    time_of_day: Optional[str] = None  # "morning", "afternoon", "evening", "late_night"
    conversation_state: Dict[str, Any] = Field(default_factory=dict)
    order_history: List[int] = Field(default_factory=list)
    favorite_restaurant_ids: List[int] = Field(default_factory=list)
    debug_mode: bool = False


class RecommendationRequest(BaseModel):
    """Structured recommendation request containing generalized constraints & context."""
    constraints: List[Constraint] = Field(default_factory=list)
    context: RecommendationContext = Field(default_factory=RecommendationContext)
    top_k: int = 50

    def get_constraint(self, constraint_type: str) -> Optional[Constraint]:
        """Utility to retrieve constraint by type if present."""
        for c in self.constraints:
            if c.type == constraint_type:
                return c
        return None

    def get_constraint_value(self, constraint_type: str, default: Any = None) -> Any:
        """Utility to retrieve constraint value by type."""
        c = self.get_constraint(constraint_type)
        return c.value if c is not None else default


class EffectiveRecommendationRequest(RecommendationRequest):
    """
    Stage 3.3 Canonical recommendation request generated by Layer 2 Lifecycle Engine.
    Used downstream by Layers 3, 4, 5, 6.
    Ensures memory stays internal and only effective, lifecycle-resolved constraints reach retrieval.
    """
    raw_user_request: Optional[RecommendationRequest] = None
    ephemeral_cleaned: List[str] = Field(default_factory=list)
    turn_number: int = 1


class RecommendationCandidate(BaseModel):
    """Raw candidate item retrieved from catalog."""
    item_id: int
    name: str
    description: str = ""
    price: int
    available: bool = True
    category: str  # "veg" or "non-veg"
    meal_type: str
    healthy: bool = False
    vegetarian: bool = True
    high_protein: bool = False
    spicy: bool = False
    vegan: bool = False
    low_calorie: bool = False
    gluten_free: bool = False
    restaurant_id: Optional[int] = None
    restaurant_name: str = ""
    cuisine: str = ""
    cuisine_type: str = ""
    taste_preference: str = ""
    parent_category: str = ""
    serving: str = ""
    is_combo: bool = False
    combo_id: Optional[int] = None
    savings_amount: Optional[int] = None
    raw_item: Dict[str, Any] = Field(default_factory=dict)


class ComponentScore(BaseModel):
    """Individually computed score component."""
    component: str
    score: float
    reason: Optional[str] = None


class RecommendationScore(BaseModel):
    """Aggregated score payload for a candidate item."""
    total_score: float
    score_breakdown: List[ComponentScore] = Field(default_factory=list)


class RecommendationReason(BaseModel):
    """Structured decision reasons and trade-offs for recommendation output."""
    reasons: List[str] = Field(default_factory=list)
    tradeoffs: List[str] = Field(default_factory=list)


class RecommendationExplanation(BaseModel):
    """Structured decision explanations for candidate items."""
    reasons: List[str] = Field(default_factory=list)
    tradeoffs: List[str] = Field(default_factory=list)



class PipelineDebugInfo(BaseModel):
    """Developer debug telemetry for testing and evaluation."""
    strategy: str
    matched_constraints: List[str] = Field(default_factory=list)
    candidate_counts: Dict[str, int] = Field(default_factory=dict)
    ranking_duration_ms: float = 0.0
    pipeline_duration_ms: float = 0.0


class FieldMatchPlan(BaseModel):
    """Layer 3: Maps extracted constraints to dataset fields in menu_items.json."""
    field_mappings: Dict[str, List[str]] = Field(default_factory=dict)
    active_constraints: Dict[str, Any] = Field(default_factory=dict)


from enum import Enum


class ResponseState(str, Enum):
    """Layer 7 single response guarantee states."""
    NOT_STARTED = "NOT_STARTED"
    GENERATING = "GENERATING"
    COMPLETED = "COMPLETED"


class ValidationResult(BaseModel):
    """Layer 6 structured validation diagnosis payload."""
    is_valid: bool
    primary_failure: Optional[str] = None
    protected_constraints: List[str] = Field(default_factory=list)
    relaxable_constraints: List[str] = Field(default_factory=list)
    candidates_before_failure: int = 0
    candidates_after_failure: int = 0
    failure_reason: str = ""
    rejection_breakdown: Dict[str, int] = Field(default_factory=dict)
    rejected_candidates_by_reason: Dict[str, List[str]] = Field(default_factory=dict)


class CandidateEvaluation(BaseModel):
    """Layer 5/6: Structured evaluation payload for a single candidate item."""
    candidate: RecommendationCandidate
    score: float
    score_breakdown: List[ComponentScore] = Field(default_factory=list)
    rank: int = 1
    ranking_reason: str = ""
    validation_status: str = "PENDING"  # "PASS" or "FAIL"
    confidence: float = 1.0
    confidence_reason: str = ""


class RecommendationExecution(BaseModel):
    """Shared pipeline execution context object updated independently by each layer."""
    normalized_request: str = ""
    recommendation_request: Optional[RecommendationRequest] = None
    memory_request: Optional[RecommendationRequest] = None
    field_match_plan: Optional[FieldMatchPlan] = None
    candidate_pool: List[RecommendationCandidate] = Field(default_factory=list)
    candidate_evaluations: List[CandidateEvaluation] = Field(default_factory=list)
    validated_candidates: List[CandidateEvaluation] = Field(default_factory=list)
    validation_result: Optional[ValidationResult] = None
    response_state: ResponseState = ResponseState.NOT_STARTED
    cached_response: Optional[str] = None
    llm_calls_count: int = 0
    pipeline_trace: List[str] = Field(default_factory=list)


class RecommendationResult(BaseModel):
    """Final ranked item payload returned by Recommendation Engine."""
    candidate: RecommendationCandidate
    score: RecommendationScore
    reason: RecommendationReason
    confidence: float = 1.0
    debug: Optional[PipelineDebugInfo] = None
